apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-role
  namespace: argocd
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Add additional rules as needed

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-role-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-app-role
  apiGroup: rbac.authorization.k8s.io
